pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick

// Companion frame resolver. Reads the versioned manifest generated by
// `scripts/derive-companion-assets.py` (`assets/companion/manifest.json`)
// and resolves (skin, animation) pairs to frame files with anchor,
// timing, and chaining metadata.
//
// Rules:
// - Unknown skins fall back to "default"; unknown animations to "idle".
// - Partial skins ship only grounded poses; their fly frames resolve to
//   the default Hornero fly frame via the manifest fallbackChain.
// - A missing or malformed manifest resolves to safe defaults without
//   errors (companion UI hides itself until ready).
Singleton {
    id: root

    readonly property var knownSkins: ["default", "argentina", "blue-gold", "red", "gaucho"]
    readonly property var knownAnimations: ["idle", "walk", "fly", "greet"]
    readonly property string defaultSkin: "default"
    readonly property string defaultAnimation: "idle"

    property var skins: ({})
    property var assistantStates: ({})
    property int manifestVersion: 0
    property bool ready: false

    readonly property string manifestDir: `${Quickshell.shellDir}/assets/companion`
    readonly property string manifestPath: `${root.manifestDir}/manifest.json`

    function isKnownSkin(skin: string): bool {
        return root.knownSkins.indexOf((skin ?? "").toString()) !== -1;
    }

    function isKnownAnimation(animation: string): bool {
        return root.knownAnimations.indexOf((animation ?? "").toString()) !== -1;
    }

    // Resolve (skin, animation) to display metadata. Never throws and
    // never returns an empty file: worst case is the default idle frame.
    function resolve(skin: string, animation: string): var {
        const s = root.isKnownSkin(skin) ? skin.toString() : root.defaultSkin;
        const a = root.isKnownAnimation(animation) ? animation.toString() : root.defaultAnimation;
        const entry = (root.skins[s] !== undefined && root.skins[s][a] !== undefined)
            ? root.skins[s][a]
            : null;
        if (entry === null || !Array.isArray(entry.frames) || entry.frames.length === 0) {
            return {
                "skin": root.defaultSkin,
                "animation": root.defaultAnimation,
                "file": `${root.manifestDir}/frames/default-idle.png`,
                "anchor": "feet",
                "anchorPx": [256, 472],
                "frameMs": 900,
                "loop": true,
                "next": "idle",
                "fallback": s !== root.defaultSkin
            };
        }
        const frame = entry.frames[0];
        return {
            "skin": s,
            "animation": a,
            "file": `${root.manifestDir}/${frame.file}`,
            "anchor": entry.anchor ?? "feet",
            "anchorPx": frame.anchorPx ?? [256, 472],
            "frameMs": entry.frameMs ?? 900,
            "loop": entry.loop ?? true,
            "next": entry.next ?? "idle",
            "fallback": typeof frame.file === "string" && !frame.file.startsWith(`frames/${s}-`)
        };
    }

    function frameSource(skin: string, animation: string): string {
        return root.resolve(skin, animation).file;
    }

    function stateSource(state: string): string {
        const animation = root.assistantStates[(state ?? "").toString()] ?? root.defaultAnimation;
        return root.frameSource(root.defaultSkin, animation);
    }

    // Tolerant parse mirroring the generator contract: manifestVersion
    // must be 1 with a skins object; anything else keeps safe defaults.
    function parse(text: string): void {
        const skins = {};
        const states = {};
        let version = 0;
        try {
            const o = JSON.parse(text);
            if (o !== null && typeof o === "object" && !Array.isArray(o)
                    && o.manifestVersion === 1 && o.skins !== null
                    && typeof o.skins === "object" && !Array.isArray(o.skins)) {
                for (const key of Object.keys(o.skins)) {
                    const skin = o.skins[key];
                    if (skin === null || typeof skin !== "object" || Array.isArray(skin))
                        continue;
                    if (skin.animations === null || typeof skin.animations !== "object")
                        continue;
                    skins[key] = skin.animations;
                }
                if (o.assistantStates !== null && typeof o.assistantStates === "object"
                        && !Array.isArray(o.assistantStates)) {
                    for (const key of Object.keys(o.assistantStates)) {
                        if (typeof o.assistantStates[key] === "string")
                            states[key] = o.assistantStates[key];
                    }
                }
                if (Object.keys(skins).length > 0)
                    version = 1;
            }
        } catch (e) {
            // Malformed manifest: companion stays on safe defaults.
        }
        root.skins = skins;
        root.assistantStates = states;
        root.manifestVersion = version;
        root.ready = true;
    }

    FileView {
        path: root.manifestPath
        watchChanges: true
        onFileChanged: reload()
        onLoaded: root.parse(text())
        onLoadFailed: {
            root.skins = {};
            root.assistantStates = {};
            root.manifestVersion = 0;
            root.ready = true;
        }
    }
}
